## Random Numbers in NumPy

In [1]:
import numpy as np

rand = np.random.randint(100) # predict nandom number
rand

91

In [2]:
float_rand = np.random.rand() # predict random float value

float_rand

0.40591020620106255

In [3]:
x=np.random.randint(100, size=(7)) # for array

x

array([ 2, 88, 26, 48, 84, 46, 80])

In [4]:
x = np.random.randint(100, size=(3, 5)) # for 2-D array
x

array([[63, 90, 48,  6,  9],
       [93, 55, 73, 73, 94],
       [66, 35, 23, 26,  1]])

### Data Distribution
* Data Distribution is a list of all possible values, and how often each value occurs.

In [5]:
#Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.1
# The probability for the value to be 5 is set to be 0.3
# The probability for the value to be 7 is set to be 0.6
# The probability for the value to be 9 is set to be 0

x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
x

array([5, 3, 7, 5, 5, 3, 7, 5, 5, 5, 7, 5, 7, 3, 3, 5, 5, 5, 7, 7, 3, 7,
       5, 5, 5, 7, 7, 5, 3, 7, 7, 5, 7, 7, 5, 7, 7, 5, 3, 5, 7, 7, 7, 5,
       5, 7, 7, 7, 7, 7, 7, 5, 7, 7, 7, 7, 7, 5, 5, 5, 3, 7, 7, 7, 3, 5,
       7, 7, 7, 7, 5, 7, 5, 7, 5, 5, 5, 7, 7, 5, 7, 5, 3, 7, 3, 7, 3, 7,
       7, 7, 7, 3, 7, 5, 5, 5, 5, 7, 5, 5])

In [6]:
# 2-D array
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
x


array([[5, 5, 3, 3, 7],
       [3, 7, 7, 7, 7],
       [5, 5, 7, 7, 7]])

In [10]:
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr) #The shuffle() method makes changes to the original array.
arr

array([4, 1, 5, 3, 2])

## ufunc sipmle arithmatic 

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])

addition = np.add(a,b)
addition

array([6, 6, 6, 6, 6])

In [12]:
subtraction = np.subtract(a,b)
subtraction

array([-4, -2,  0,  2,  4])

In [13]:
multipliaction = np.multiply(a,b)
multipliaction

array([5, 8, 9, 8, 5])

In [14]:
division = np.divide(a,b)
division

array([0.2, 0.5, 1. , 2. , 5. ])

In [16]:
mod = np.divmod(a,b)
mod

(array([0, 0, 1, 2, 5]), array([1, 2, 0, 0, 0]))

### ufunc rounding Decimals

In [17]:
arr = np.around(3.1666, 3)
arr

3.167

In [19]:
arr = np.floor(33.342) # The floor() function rounds off decimal to nearest lower integer.
arr

33.0

In [21]:
arr = np.ceil(33.842)  # The ceil() function rounds off decimal to nearest upper integer.
arr

34.0