## Random Numbers in NumPy

In [1]:
import numpy as np

rand = np.random.randint(100) # predict nandom number
rand

99

In [2]:
float_rand = np.random.rand() # predict random float value

float_rand

0.033787488652156195

In [3]:
x=np.random.randint(100, size=(7)) # for array

x

array([71, 97, 95, 43, 84, 23, 29])

In [4]:
x = np.random.randint(100, size=(3, 5)) # for 2-D array
x

array([[87, 57, 24, 18,  2],
       [15, 85, 77, 40, 78],
       [13, 95, 88, 49, 25]])

### Data Distribution
* Data Distribution is a list of all possible values, and how often each value occurs.

In [7]:
#Generate a 1-D array containing 100 values, where each value has to be 3, 5, 7 or 9.
# The probability for the value to be 3 is set to be 0.1
# The probability for the value to be 5 is set to be 0.3
# The probability for the value to be 7 is set to be 0.6
# The probability for the value to be 9 is set to be 0

x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100))
x

array([7, 7, 7, 3, 7, 3, 5, 3, 5, 5, 7, 5, 5, 5, 7, 7, 7, 7, 5, 5, 7, 7,
       7, 3, 7, 7, 3, 7, 5, 7, 7, 7, 7, 3, 7, 7, 5, 7, 7, 7, 5, 7, 7, 5,
       7, 5, 5, 7, 7, 7, 5, 5, 3, 7, 5, 5, 5, 7, 7, 7, 3, 5, 7, 7, 7, 3,
       7, 7, 7, 7, 5, 3, 5, 5, 7, 7, 5, 7, 7, 5, 7, 5, 7, 3, 7, 3, 5, 7,
       7, 5, 7, 7, 7, 3, 5, 7, 7, 5, 7, 7])

In [10]:
# 2-D array
x = np.random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
x


array([[7, 3, 5, 7, 5],
       [7, 5, 7, 5, 7],
       [5, 5, 7, 7, 5]])