## Start NumPy
* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

In [42]:
import numpy as np

num_array = np.array([1,2,3,4,5])

num_array

array([1, 2, 3, 4, 5])

In [43]:
type(num_array)

numpy.ndarray

In [44]:
np.__version__ # version checking

'1.26.1'

In [45]:
arr_1D = np.array([1, 2, 3, 4, 5]) # one dimensional array

In [46]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]]) # two dimensional array
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]) #3 dimensional array
arr_3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [48]:
arr_1D.ndim


1

In [49]:
arr_2D.ndim

2

In [50]:
arr_3D.ndim

3

In [51]:
arr_2D[1][0] 

4

In [52]:
arr_2D[1][0] + arr_2D[1][0] # how to add 2 D array index value

8

In [53]:
arr_2D[1,0]

4

In [54]:
arr_3D[0,1,2] #this for third dimension

6

In [55]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

### Negative indexing

In [56]:
arr_2D[1][-1]

6

### Array Slicing

In [57]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [58]:
arr[1:4]

array([2, 3, 4])

In [59]:
arr[0:-1]

array([1, 2, 3, 4, 5, 6])

In [60]:
arr[::2]

array([1, 3, 5, 7])

In [61]:
arr_2D[1, 1:4]

array([5, 6])

In [62]:
arr.dtype

dtype('int32')

In [63]:
arr_3D.dtype

dtype('int32')

In [64]:
arr.astype(float) #existing datetype into another datatype

array([1., 2., 3., 4., 5., 6., 7.])

## Copy vs View 

In [65]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()   #The copy SHOULD NOT be affected by the changes made to the original array.
arr[0] = 42
arr

array([42,  2,  3,  4,  5])

In [66]:
x

array([1, 2, 3, 4, 5])

#### View

In [67]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()  #The view SHOULD be affected by the changes made to the original array.
arr[0] = 42
arr

array([42,  2,  3,  4,  5])

In [68]:
x

array([42,  2,  3,  4,  5])

In [69]:
arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr.shape

(2, 5)

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)  #Reshaping means changing the shape of an array.
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Array itering 

In [71]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Array Join

In [72]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,1])

join_array = np.concatenate((arr1,arr2))

In [73]:
join_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [74]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [75]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

### spliting array

In [76]:
arr = np.array([1, 2, 3, 4, 3, 6])

newarr = np.array_split(arr, 4)
newarr

[array([1, 2]), array([3, 4]), array([3]), array([6])]

### Searching array

In [77]:
search_array = np.where(arr==3)
search_array

(array([2, 4], dtype=int64),)

In [78]:
arr = np.array([2,4,5,7,3,1])
srt_array = np.sort(arr)
srt_array

array([1, 2, 3, 4, 5, 7])

In [79]:
arr = np.array(['d','s','a','c','f','e'])
srt_array = np.sort(arr)
srt_array

array(['a', 'c', 'd', 'e', 'f', 's'], dtype='<U1')