## Start NumPy
* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

In [2]:
import numpy as np

num_array = np.array([1,2,3,4,5])

num_array

array([1, 2, 3, 4, 5])

In [3]:
type(num_array)

numpy.ndarray

In [4]:
np.__version__ # version checking

'1.26.1'

In [5]:
arr_1D = np.array([1, 2, 3, 4, 5]) # one dimensional array

In [6]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]]) # two dimensional array
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]) #3 dimensional array
arr_3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [8]:
arr_1D.ndim


1

In [9]:
arr_2D.ndim

2

In [10]:
arr_3D.ndim

3

In [11]:
arr_2D[1][0] 

4

In [12]:
arr_2D[1][0] + arr_2D[1][0] # how to add 2 D array index value

8

In [13]:
arr_2D[1,0]

4

In [14]:
arr_3D[0,1,2] #this for third dimension

6

In [15]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

### Negative indexing

In [16]:
arr_2D[1][-1]

6

### Array Slicing

In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [18]:
arr[1:4]

array([2, 3, 4])

In [19]:
arr[0:-1]

array([1, 2, 3, 4, 5, 6])

In [20]:
arr[::2]

array([1, 3, 5, 7])

In [21]:
arr_2D[1, 1:4]

array([5, 6])

In [22]:
arr.dtype

dtype('int32')

In [23]:
arr_3D.dtype

dtype('int32')

In [24]:
arr.astype(float) #existing datetype into another datatype

array([1., 2., 3., 4., 5., 6., 7.])

## Copy vs View 

In [30]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()   #The copy SHOULD NOT be affected by the changes made to the original array.
arr[0] = 42
arr

array([42,  2,  3,  4,  5])

In [31]:
x

array([1, 2, 3, 4, 5])

#### View

In [32]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()  #The view SHOULD be affected by the changes made to the original array.
arr[0] = 42
arr

array([42,  2,  3,  4,  5])

In [33]:
x

array([42,  2,  3,  4,  5])

In [38]:
arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr.shape

(2, 5)