## Start NumPy
* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

In [3]:
import numpy as np

num_array = np.array([1,2,3,4,5])

num_array

array([1, 2, 3, 4, 5])

In [4]:
type(num_array)

numpy.ndarray

In [5]:
np.__version__ # version checking

'1.26.1'

In [7]:
arr_1D = np.array([1, 2, 3, 4, 5]) # one dimensional array

In [10]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]]) # two dimensional array
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]) #3 dimensional array
arr_3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [15]:
arr_1D.ndim
arr_2D.ndim
arr_3D.ndim

3