## Start NumPy
* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

In [3]:
import numpy as np

num_array = np.array([1,2,3,4,5])

num_array

array([1, 2, 3, 4, 5])

In [4]:
type(num_array)

numpy.ndarray

In [5]:
np.__version__ # version checking

'1.26.1'

In [7]:
arr_1D = np.array([1, 2, 3, 4, 5]) # one dimensional array

In [10]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]]) # two dimensional array
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]) #3 dimensional array
arr_3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [16]:
arr_1D.ndim


1

In [17]:
arr_2D.ndim

2

In [18]:
arr_3D.ndim

3

In [25]:
arr_2D[1][0] 

4

In [34]:
arr_2D[1][0] + arr_2D[1][0] # how to add 2 D array index value

8

In [27]:
arr_2D[1,0]

4

In [33]:
arr_3D[0,1,2] #this for third dimension

6

In [35]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

### Negative indexing

In [36]:
arr_2D[1][-1]

6