## Start NumPy
* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

In [1]:
import numpy as np

num_array = np.array([1,2,3,4,5])

num_array

array([1, 2, 3, 4, 5])

In [2]:
type(num_array)

numpy.ndarray

In [3]:
np.__version__ # version checking

'1.26.1'

In [4]:
arr_1D = np.array([1, 2, 3, 4, 5]) # one dimensional array

In [5]:
arr_2D = np.array([[1, 2, 3], [4, 5, 6]]) # two dimensional array
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr_3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]]) #3 dimensional array
arr_3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [7]:
arr_1D.ndim


1

In [8]:
arr_2D.ndim

2

In [9]:
arr_3D.ndim

3

In [10]:
arr_2D[1][0] 

4

In [11]:
arr_2D[1][0] + arr_2D[1][0] # how to add 2 D array index value

8

In [12]:
arr_2D[1,0]

4

In [13]:
arr_3D[0,1,2] #this for third dimension

6

In [14]:
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

### Negative indexing

In [15]:
arr_2D[1][-1]

6

### Array Slicing

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [17]:
arr[1:4]

array([2, 3, 4])

In [18]:
arr[0:-1]

array([1, 2, 3, 4, 5, 6])

In [19]:
arr[::2]

array([1, 3, 5, 7])

In [20]:
arr_2D[1, 1:4]

array([5, 6])

In [21]:
arr.dtype

dtype('int32')

In [22]:
arr_3D.dtype

dtype('int32')

In [23]:
arr.astype(float) #existing datetype into another datatype

array([1., 2., 3., 4., 5., 6., 7.])

## Copy vs View 

In [24]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()   #The copy SHOULD NOT be affected by the changes made to the original array.
arr[0] = 42
arr

array([42,  2,  3,  4,  5])

In [25]:
x

array([1, 2, 3, 4, 5])

#### View

In [26]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()  #The view SHOULD be affected by the changes made to the original array.
arr[0] = 42
arr

array([42,  2,  3,  4,  5])

In [27]:
x

array([42,  2,  3,  4,  5])

In [28]:
arr = np.array([[1,2,3,4,5],[5,4,3,2,1]])
arr.shape

(2, 5)

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)  #Reshaping means changing the shape of an array.
newarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### Array itering 

In [31]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### Array Join

In [33]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,1])

join_array = np.concatenate((arr1,arr2))

In [34]:
join_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1])

In [35]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))
arr

array([[[1, 4],
        [2, 5],
        [3, 6]]])

### spliting array

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]